# Generated by Django 2.2.7 on 2019-11-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
