# Generated by Django 2.2.7 on 2019-11-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
